name: CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Images
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/api/Dockerfile
          push: true
          tags: ghcr.io/abhishek8841/shipyard-app-api:latest

      - name: Build and push BUILDER image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/builder/Dockerfile
          push: true
          tags: ghcr.io/abhishek8841/shipyard-app-builder:latest

      - name: Build and push PROXY image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/proxy/Dockerfile
          push: true
          tags: ghcr.io/abhishek8841/shipyard-app-proxy:latest

      - name: Build and push GIT-NODE-RUNTIME image
        uses: docker/build-push-action@v6
        with:
          context: ./runtimes
          file: ./runtimes/Dockerfile
          push: true
          tags: ghcr.io/abhishek8841/shipyard-builder-image:latest
        
      - name: Test SSH connection
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            echo "SSH connection successful"
            hostname
            docker --version